<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.hivecloud</groupId>
        <artifactId>hivecloud-plugins</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>hivecloud-plugin-encrypt</artifactId>

    <name>HiveCloud Plugin Encrypt</name>
    <description>加密插件</description>

    <dependencies>
        <dependency>
            <groupId>com.hivecloud</groupId>
            <artifactId>hivecloud-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.hivecloud</groupId>
            <artifactId>hivecloud-plugin-engine</artifactId>
        </dependency>
    </dependencies>
</project>
