<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.hivecloud</groupId>
        <artifactId>hivecloud-ms</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>hivecloud-modules</artifactId>
    <packaging>pom</packaging>

    <name>HiveCloud Modules</name>
    <description>模块化单体</description>

    <modules>
        <module>hivecloud-module-system</module>
    </modules>
</project>
